name: Create ALF File

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unity-version:
        - 2018.4.18f1
        - 2019.3.3f1
    steps:
    - uses: pCYSl5EDgo/setup-unity@master
      with:
        unity-version: ${{ matrix.unity-version }}
    - run: /opt/Unity/Editor/Unity -quit -batchMode -nographics -logfile -createManualActivationFile || exit 0
    - run: |
        mkdir a
        mv Unity_v${{ matrix.unity-version }}.alf a/
    - uses: actions/upload-artifact@master
      with:
        path: a
        name: ${{ matrix.unity-version }}
