name: Create ALF File

on: [push]

jobs:
#   build-windows-test:
#     runs-on: [windows-latest]
#     steps:
#     - run: bitsadmin /TRANSFER bj /download /priority normal https://download.unity3d.com/download_unity/ffacea4b84e7/Windows64EditorInstaller/UnitySetup64.exe %CD%\UnitySetup64.exe
#       shell: cmd
#     - run: ./UnitySetup64.exe /L /UI=reduced /S
#       continue-on-error: true
#   build-mac-test:
#     runs-on: [macOS-latest]
#     steps:
#     - run: curl -OL https://beta.unity3d.com/download/ffacea4b84e7/MacEditorInstaller/Unity.pkg
#     - run: sudo installer -package Unity.pkg -target /
#     - run: /Applications/Unity/Unity.app/Contents/MacOS/Unity -quit -batchMode -createManualActivationFile -logfile || exit 0
#     - run: cat Unity_v${{ matrix.unity-version }}.alf

#   build-ubuntu-test:
#     runs-on: [ubuntu-latest]
#     steps:
#     - run: wget https://beta.unity3d.com/download/ffacea4b84e7/UnitySetup -O UnitySetUp
#     - run: sudo chmod +x UnitySetUp
#     - run: ls -l
#     - run: sudo ./UnitySetUp --help || exit 0
#     - run: ./UnitySetUp -v -L
#     - run: echo y | ./UnitySetUp --unattended --install-location="/opt/Unity" --components="Unity,Android,WebGL"
#     - run: ls -l /opt/Unity/Editor/ || exit 0
#     - run: ls -l /opt/Unity/Editor/Data/PlaybackEngines/AndroidPlayer || exit 0
#   build-macos-all:
#     runs-on: [macOS-latest]
#     strategy:
#       matrix:
#         unity-version: [2018.4.9f1, 2019.2.13f1, 2020.1.0a14]
#     steps:
#     - uses: actions/setup-ruby@v1
#       with:
#         ruby-version: '2.6.3'
#     - run: gem install u3d -v 1.2.1
#     - run: u3d available
#     - run: sudo /Users/runner/hostedtoolcache/Ruby/2.6.3/x64/bin/u3d install ${{ matrix.unity-version }} --all
#   build-windows-all:
#     runs-on: [windows-latest]
#     strategy:
#       matrix:
#         unity-version: [2018.4.9f1, 2019.2.13f1, 2019.3.0b12, 2020.1.0a14]
#     steps:
#     - uses: actions/setup-ruby@v1
#       with:
#         ruby-version: '2.6.3'
#     - run: gem install u3d -v 1.2.1
#     - run: u3d install ${{ matrix.unity-version }} --all
#   build-linux-all:
#     runs-on: [ubuntu-latest]
#     strategy:
#       matrix:
#         unity-version: [2019.1.0f2, 2018.3.0f2, 2018.1.0b8]
#     steps:
#     - uses: actions/setup-ruby@v1
#       with:
#         ruby-version: '2.6.3'
#     - run: gem install u3d -v 1.2.1
#     - run: sudo apt-get update
#     - run: sudo apt-get -y install gconf-service lib32gcc1 lib32stdc++6 libasound2 libc6 libc6-i386 libcairo2 libcap2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libfreetype6 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libgl1-mesa-glx libglib2.0-0 libglu1-mesa libgtk2.0-0 libnspr4 libnss3 libpango1.0-0 libstdc++6 libx11-6 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxtst6 zlib1g debconf npm libpq5
#     - run: sudo /opt/hostedtoolcache/Ruby/2.6.3/x64/bin/u3d install ${{ matrix.unity-version }} --all

#   build-windows-test1:
#     runs-on: windows-latest
#     steps:
#     - shell: cmd
#       run: bitsadmin /TRANSFER bj /download /priority normal https://download.unity3d.com/download_unity/497f083a43af/Windows64EditorInstaller/UnitySetup64.exe %CD%\UnitySetup64.exe
#     - shell: cmd
#       run: |
#         dir
#         UnitySetup64.exe /UI=reduced /S /D=C:\Program Files\Unity_2018.4.13f1
#     - run: dir "C:\Program Files\"
#     - run: |
#         & 'C:\Program Files\Unity_2018.4.13f1\Editor\Unity.exe' -quit -batchMode -nographics -logfile -createManualActivationFile
#     - run: cat Unity_v2018.4.13f1.alf
  
 # build-windows:
#    runs-on: windows-latest
   # strategy:
 #     matrix:
  #      unity-version: [2018.4.9f1, 2020.1.0a14]
 #   steps:
 #   - id: z
#      uses: pCYSl5EDgo/setup-unity@master
   #   with:
 #       unity-version: ${{ matrix.unity-version }}
  #  - run: dir 'C:\Program Files\Unity\Editor\Data\Tools\RoslynScripts'
 #     continue-on-error: true
#    - run: dir 'C:\Program Files\Unity\Editor\Data\Tools\Roslyn'
   #   continue-on-error: true
#     - run: get-content 'C:\Program Files\Unity\Editor\Data\Tools\RoslynScripts\unity_csc.bat'
    
#  build-mac:
   # runs-on: [macos-latest]
 #   strategy:
  #    matrix:
 #       unity-version: [2018.4.9f1, 2020.1.0a14]
  #  steps:
 #   - uses: pCYSl5EDgo/setup-unity@master
 #     with:
  #      unity-version: ${{ matrix.unity-version }}
  #  - run: |
 #       ls -l /Applications/Unity/Unity.app/Contents/Tools/RoslynNet46
#        ls -l /Applications/Unity/Unity.app/Contents/Tools/Roslyn
        #cat /Applications/Unity/Unity.app/Contents/Tools/RoslynScripts/unity_csc

  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unity-version: 
        - 2018.4.15f1
    steps:
    - uses: pCYSl5EDgo/setup-unity@master
      with:
        unity-version: ${{ matrix.unity-version }}
    - run: |
        ls -l /opt/Unity/Editor/Data/Tools/Roslyn
        ls -l /opt/Unity/Editor/Data/Tools/RoslynNet46
    - run: /opt/Unity/Editor/Unity -quit -batchMode -nographics -logfile -createManualActivationFile || exit 0
    - run: |
        mkdir a
        mv Unity_v${{ matrix.unity-version }}.alf a/
    - uses: actions/upload-artifact@master
      with:
        path: a
        name: ${{ matrix.unity-version }}

#     - run: echo -n $ULF aaa > Unity.ulf
#       env:
#         ULF: ${{ secrets.ulf_linux }}
#     - run: /opt/Unity/Editor/Unity -nographics -quit -batchmode -manualLicenseFile Unity.ulf -logfile || exit 0
#     - run: /opt/Unity/Editor/Unity -nographics -quit -batchmode -password "$PWD" -username pcysl5edgo@yahoo.co.jp -logfile || exit 0
#       env:
#         PWD: ${{ secrets.pwd }}
#   build-gableroux:
#     runs-on: [ubuntu-latest]
#     strategy:
#       matrix:
#         unity-version: 
#         - 2018.4.9f1
#         - 2018.4.10f1
#         - 2018.4.12f1
#     container: docker://gableroux/unity3d:${{ matrix.unity-version }}
#     steps:
#     - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -logfile -createManualActivationFile || exit 0
#     - run: cat Unity_v${{ matrix.unity-version }}.alf
#     - run: |
#         mkdir a
#         mv Unity_v${{ matrix.unity-version }}.alf a/
#     - uses: actions/upload-artifact@master
#       with:
#         path: a
#         name: ${{ matrix.unity-version }}
